spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.234.23.193:3306/user_center
    username: ck
    password: 15860057952ck
    # 失效时间
  session:
    timeout: 86400
    # redis配置
  redis:
    port: 6379
    host: 49.234.23.193
    database: 0
    password: 15860057952ck
    timeout: 20000
server:
  address: 0.0.0.0

